apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQmdNVkxsR2hHVWd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1UWXdORE15TWpkYUZ3MHpOVEV4TVRRd05ETTNNamRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUQzSlZ1bkhPaGxmSjFKNjhiVzFJZWJVejYzUElrQVFMQXcxRnFsenpvc0JuRGNhRXFIbnFsbE90bkUKVEpmbjFnMWtaT2VjTUlNcWZ0b2RrNzlFMmhHL29SYnBPRENGeGFibG1PRFFTWnpnMTV2Z3lEWndmZkpmeS9BYwpONHo5Uy9LR3lFY2dUWGQrTGtHOW96Wi9reENOYmpEZjJGcGhjeWZUOFRMTUdremJVV1ZTWWJCNTZFTmNlQ0FuCnIzNmxURkVuVisydDdWUEU2L2g1TmI5MFduWGRVZHFrOTRxbVoxRzVkTHZ6NzF5bitoY0NMUXZ1bXZESGJmV0sKaHY5NTRYL2lLUEhOOFBicmZrWEQ0Tit3UC8zMFJYTTJCVTE0L09tWnhPRlJuVGlsVEQ5SXZrYjFZS1FJMkt4VApnbEdqaUlEWWc4UE1QNDZuU3Naa2R6Zm5Hb1BMQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSWGVnWU83K1hETENaVVBZUVNtbXZQcDcrcnBUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRRE43ZU14OHNUdApBZysvZzZnM2h0MkNRYm1yc1krYUZ5UTVxc3JQakp0VTB0aUJxN01NRVY2VVNVQkxiUmFQVVdlVXplRDg2SEY2CkZIK0dGNzByRytxaTVwdGU1MXJvVTlUd1l2MVdxSTNCZWRidncyYnFZMHRHZHJjbWljakwxWWhDQzIzemV2MGEKS0RBL2t2QWpOUXRpREN6MU1idERtV0xTVkpHUjc1SWZQa3NiSEhhdWcyL0JHTlhFVVFudjZUd3VDMFhnY1YvWApwRlJlVXlKejN3Z0RoVmQ3ZVhEYXI2SmJwY2lEdWZsRmZBNjlVSUk4cDV0dHBpV2J0aGFYVWJWTEJlalJrdVNsClV5Z253akhiSmtaeVdSTE9yZndXMllMN0Y3M2Q5WGhFOGs3SllIQ2szd0ViQ0toa0lVeTNEV1N1K3kycHFpWVYKQ2k1WHkxdTJWbXpLCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://32f18e0b-0ec9-4ab2-ba32-86cde5454ac3.us-west-1-gw.linodelke.net:443
  name: lke534358

users:
- name: lke534358-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImZzblR1UzZzeHliQVpKQ0VUd243c2tPY3FFMms2REdEUmxrcVVxa0tlbWcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tZmxxYmgiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMWVlYjRmOGItOGJlYy00Y2NkLThlMTUtNWU1MTdmNTc1NTZmIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.Y5D8CGHpp806-u99q83Tq1HW7xsPzYOTUNRUCG5ykTJ4yRu8LLNN_3SH96zYbnoRtAHH3Zzn74rnlgzX0Pegl_tmZQY7HhY-jSggcD23uH658gh9euAtDZ5lQ_FrnAXKwwH3jZb-DtujPBuZgM7EFgsiotisfgE6yCw4EQMc9zF3m0hk51-mO2HtTwnmW-q2niVw0S30AHsROD0W_KfpikKsigTXCEbCRyXc-GTPqtGhoRc7sECDWl5S8lq6oQ4T1p_gluHyrm-0J5jdBSvcP89e-5_XKUD1IZhf2UQxK5Do6P7J0S03Xwj1U4n8G_853pVZskJUs9SZy5-nkNHNxw

contexts:
- context:
    cluster: lke534358
    namespace: default
    user: lke534358-admin
  name: lke534358-ctx

current-context: lke534358-ctx
